--- #YAML:1.0
name:               Dancer-Plugin-Database
version:            1.82
abstract:           easy database connections for Dancer applications
author:
    - David Precious <davidp@preshweb.co.uk>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Dancer:      1.305
    DBI:         0
    Test::More:  0
resources:
    bugtracker:  https://github.com/bigpresh/Dancer-Plugin-Database/issues
    homepage:    https://github.com/bigpresh/Dancer-Plugin-Database/
    repository:  https://github.com/bigpresh/Dancer-Plugin-Database
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
